### ISSUE TITLE
/reportコマンドの機能拡充

### ISSUE THREAD

**Issue by ghost** [XelticaMC/X-Core#103]
理由が不足しているため、手動で打ち込めるコマンドもほしい(CoreProtectの構文が扱いやすい？)
例
/report u:<user(Tab補完可能)> t:<time(1d 1m 1h NL(無期限)のTab保管可能)> r:<reason（特に補完無し）>
/report u:LZMAShili t:NL r:私怨
2022年2月3日追記、警告に関しては従来通り選択方式の方が間違いが少なくなるため引数に追加は今のところ無しかなと

**Comment by Xeltica** [comment]
権限あるプレイヤーとコンソールが対象

**Comment by EbiseLutica** [comment]
#11 に統合
