### ISSUE TITLE
各機能ごとにモジュール化する

### ISSUE THREAD

**Issue by EbiseLutica** [XelticaMC/X-Core#109]
そろそろスパゲティになってきたので、ディレクトリ含めて再編する

### モジュール

✅**新規追加。** これまで各機能の実装がバラバラになっていたのを、機能別にまとめあげたもの。

モジュールは機能に対応するイベントハンドラー、コマンドを登録・登録解除し、データを読み書きする。

モジュールはXCorePlugin.java内で有効化・無効化される。

### コア

✅**新規追加。** モジュール全体を通して使いうる機能を提供する。X Phoneアプリ、コマンド、エビパワーなど。

### コマンド

✨**続投。** XCorePlugin.javaではなく、対応するモジュール経由で登録される。

### ハンドラー

✨**続投。** XCorePlugin.javaではなく、対応するモジュール経由で登録される。

### PluginBase

🚫**廃止。** 現在唯一存在するVaultPluginは、VaultServiceとして移動する。

### ~~Store

🚫**廃止。** 必要に応じてモジュールとAPIに分ける

## src/main/java ディレクトリ構成

機能別にディレクトリ分け

* /
  * XCorePlugin
* /core
  * モジュールが共通して使うような機能をまとめる
  * Command API
  * Player Store API
  * Hint API
  * X Phone API
  * Ebi Power API
  * Ranking API
  * World API
  * User Interface API
  * 外部プラグイン連携
    * Vault
    * DiscordSRV
    * LuckPerms 
  * その他便利関数
* /modules
  * カウンター作成
  * ロビー管理
  * モブボール
  * ミュージック
  * ニックネーム
  * ナイトメア
  * おみくじ
  * ボート・トロッコ管理
  * ゲーム内日付変更イベント発行
  * リアル日付変更イベント発行
  * ネコモード
  * 配信モード
  * カウントダウン
  * 市民制度
  * localtimeコマンド追加
  * クイックチャット
  * 通報
  * リスポーン
  * エビパワーストア
  * エビパワードラッグストア
  * ログインボーナス
  * ワイルドエリアB旅行券
  * 統合版向け免責事項
  * signeditコマンド追加
  * xtpコマンド追加
  * pvpコマンド追加

## 削除するもの

* 旅行券
  * 今や使われていない。設計し直したいので、必要になったら再実装する
  *

**Comment by Xeltica** [comment]
#160 にとって替える
