### ISSUE TITLE
モブボール(捕獲済み/空にしたケース)をディスペンサーの中に入れて出すとボールが消滅する

### ISSUE THREAD

**Issue by LZMAShili** [XelticaMC/X-Core#117]
逃がす手段として仕様にする（その場合野生に返すプログラム）か、そもそも出ないようにするかかなと。
なお、Mobが出てくる/空のものは出てこないという部分は正常なので問題なし。

**Comment by LZMAShili** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/98644057/156516429-f53fd73c-4b8a-4442-9854-e183373bf7cf.png">

**Comment by Xeltica** [comment]
スポーンエッグってディスペンサー対応してたんすね。特殊処理を挟んだほうがいいかも

**Comment by LZMAShili** [comment]
とき氏によると、空のモブボールからMobが出てきたらしいので完全にバグです。

**Comment by Xeltica** [comment]
空のモブボールもバニラからしたら結局スポーンエッグだから再現しうるな
