### ISSUE TITLE
JavaのコードをKotlinに置き換える

### ISSUE THREAD

**Issue by EbiseLutica** [XelticaMC/X-Core#121]
両方で書けるが、できれば全てKotlinに置き換えたほうが良い

**Comment by Xeltica** [comment]
## ポリシー

* 各タスクで変更する箇所は可能ならJava→Kotlinにする
* JavaからKotlinに変換するコミットと、実際の変更のコミットは分ける（レビューしやすさを向上するため）

**Comment by EbiseLutica** [comment]
v3 ですべて完了しました :tada:
