### ISSUE TITLE
MetaModule: 機能を XCorePlugin.kt に

### ISSUE THREAD

**Issue by EbiseLutica** [XelticaMC/X-Core#189]
モジュールに入れるのもなって思うので

**Comment by raink1208** [comment]
モジュールから外すのはありだけど
XCorePluginに含めずクラスは分けたい


タイトルがXCodePlugin.ktになってる

**Comment by EbiseLutica** [comment]
クラス分けるとなるとモジュールに置くしか思いつかない:innocent:

**Comment by EbiseLutica** [comment]
とりあえず明暗が思いつくまでModuleで
