### ISSUE TITLE
gmコマンドでゲームモードを切り替えたとき、マップのプレイヤーの表示状況が変わらない

### ISSUE THREAD

**Issue by Lisitsa-requin** [XelticaMC/X-Core#217]
# 概要
- `gm0`、`gm1`、`/gm3`コマンドを入力してゲームモードを切り替えた時、`dynmap show`もしくは`dynmap hide`の処理が行われていない。
- どのバージョンから発生したのかは不明
# 動作環境
Java版 1.19.3
バニラの状態で確認

**Comment by Lisitsa-requin** [comment]
補足
ゲームモードの切り替え自体は成功しており、`dynmap show`および`dynmap hide`自体の処理も成功する

**Comment by 104toki** [comment]
dynmapコマンドを実行している関数が無いっぽい？
実際、下のコードを適当なハンドラーに入れたら実行自体はした。(プラグイン入れてないから「コマンドがねーよ（#^ω^）」って怒られたけど)

```kotlin
@EventHandler
    fun onPlayerGameModeChange(e: PlayerGameModeChangeEvent) {
        if (e.newGameMode == GameMode.SPECTATOR) {
            e.player.performCommand("dynmap hide");
        } else if (e.player.hasPermission("dynmap.show")) {
            e.player.performCommand("dynmap show");
        }
    }

**Comment by EbiseLutica** [comment]
v3で間違えて削除してしまったかもしれないです
