### ISSUE TITLE
ヒント「農家の一日」の取得条件が表示と一致しない

### ISSUE THREAD

**Issue by Knit-prg** [XelticaMC/X-Core#220]
## 概要

- 検証した全てのブロック(成熟していない作物、土全種、砂、焼石、丸石、石レンガ)で、破壊時にヒントが達成されてしまう。
(ブロックによっては「エビパワーマイニング」と同時に達成可能)
- 挙動がおかしいのはヒントのみで、通常のエビパワー取得は成熟した作物でのみ可能。

#### 関係ありそうなコード
- `work.xeltica.craft.core.modules.ebipower.EbiPowerHandler:169`(`onHarvestCrops`)

**Comment by 104toki** [comment]
174行目に成長しているか検証しているが、その前（173行目）にヒントをアーカイブ化する関数を動かしてる。行を逆にすることで治りそう
https://github.com/XelticaMC/X-Core/blob/d185c60e027252e59815216c8083640ff8a0829f/src/main/java/work/xeltica/craft/core/modules/ebipower/EbiPowerHandler.kt#L172-L175

**Comment by EbiseLutica** [comment]
うわあ最悪なミス・・・

**Comment by EbiseLutica** [comment]
https://github.com/XelticaMC/X-Core/blob/cd79aa0af62ea509f8da5cc7dba50a930781b38c/src/main/java/work/xeltica/craft/core/modules/ebipower/EbiPowerHandler.kt#L174

ここに `crops.contains(e.block.type)` 判定を追加した上で、cropsから茎を削除したい

**Comment by Knit-prg** [comment]
https://github.com/XelticaMC/X-Core/blob/20ba372f78345e9ec30ef9baaf48602efde8e420/src/main/java/work/xeltica/craft/core/modules/ebipower/EbiPowerHandler.kt#L170
みたいにやっちゃったけどこれでも大丈夫かな

**Comment by Knit-prg** [comment]
cropsから茎を削除するとこんな感じらしいけど大丈夫かな
https://github.com/XelticaMC/X-Core/blob/0b7558504bdf3f3d092e8624b67bf2d4f7472cc3/src/main/java/work/xeltica/craft/core/modules/ebipower/EbiPowerHandler.kt#L54-L57
