### ISSUE TITLE
カカオ豆、ネザーウォートもEP入手対象にする

### ISSUE THREAD

**Issue by EbiseLutica** [XelticaMC/X-Core#228]
#226 により、現在エビパワー入手可能な作物が

* 小麦
* ニンジン
* ジャガイモ
* ビートルート

のみとなっている。以前は成長可能なブロック全てで手に入っていたため、カカオ豆やネザーウォートなどもエビパワー入手の対象であった。

カカオ豆、ネザーウォートをとりあえずEP入手対象として再度追加対象にしたい。

その他の追加希望や、反対意見をコメントにて受け付ける。

**Comment by 104toki** [comment]
破壊することを前提としていない、例えばスイートベリーやグロウベリーなどを入れるつもりはないのでしょうか？

**Comment by EbiseLutica** [comment]
問題なさそうなら入れるのアリかも…

**Comment by Knit-prg** [comment]
竹、サボテン、コンブ、サトウキビといった作物と呼べそうなもので、一括破壊が可能なものはどう扱うか

**Comment by EbiseLutica** [comment]
@Knit-prg 

個人的にそのへんは小麦とかと乖離しすぎているので、対象にしたくないかも
やるとして、木と同様にブロック枠かなーと思う

**Comment by EbiseLutica** [comment]
会議にて「カカオ豆、ネザーウォートを対象として追加する」で決定しました
