### ISSUE TITLE
コマンド：lowercase()の引数にLocale.getDefault()を指定している箇所がいくつかある。

### ISSUE THREAD

**Issue by 104toki** [XelticaMC/X-Core#234]
検索をかけたら以下のモジュールコマンドで発見できた。
- CounterCommand.kt
- QuickChatCommand.kt
- CandyStoreCommand.kt
- EbiPowerModule.kt
- CommandRegistry.kt
- CommandLocalTime.kt
- EpEffectShopCommand.kt

検索URL
https://github.com/XelticaMC/X-Core/search?q=Locale.getDefault&type=code

**Comment by EbiseLutica** [comment]
Javaから変換した結果こうなっちゃうのね…。
