### ISSUE TITLE
バグ：不安な同盟の進捗がネザー→共有ワールドで達成できない

### ISSUE THREAD

**Issue by 104toki** [XelticaMC/X-Core#238]
そもそも達成条件が「world」限定されている。おそらくmultiverseで作成したワールドは対象外になってる可能性が高そう。

**Comment by EbiseLutica** [comment]
マイクラ側の不具合っぽさそうだけどもう少しよく調べてみるか

**Comment by EbiseLutica** [comment]
Multiverse-NetherPortalsの問題っぽい

X-Coreでいい感じに実装するほうが早いか

**Comment by EbiseLutica** [comment]
進捗達成が許可されており、かつワールドタイプがoverworldな場合にガストを倒すと同進捗を達成するようにするか
