### ISSUE TITLE
配信モードを退出から1分後に無効化する

### ISSUE THREAD

**Issue by Xeltica** [XelticaMC/X-Core#31]
退出から1分以内に再参加した場合は無効化しない

**Comment by kumitatepazuru** [comment]
できるかわからないのですが大雑把なやり方は思いついたのでやってみてもいいですか？

**Comment by Xeltica** [comment]
どんな感じで取り掛かる予定です？

**Comment by kumitatepazuru** [comment]
新しく配信者モードのためのHandlerを作りそこにPlayerStoreのliveBarMapに乗っているプレイヤーが退出したときにBukkit.getScheduler().runTaskLaterで1分後にliveBarMapから削除するようにして、もしそのプレイヤーが再度来たときはBukkit.getScheduler().cancelTaskでタスクを止めればできると思います
雑な解説ですみません

**Comment by Xeltica** [comment]
良さげ:+1: お願いします
