### ISSUE TITLE
わかばロールの制限を緩和する

### ISSUE THREAD

**Issue by Xeltica** [XelticaMC/X-Core#32]
* メインワールドにて、ボタンの操作を許可する
* メインワールドにて、TNTをレッドストーンによって起爆できないようにする

**Comment by kumitatepazuru** [comment]
TNTが起爆しないようにすることについて。

BlockRedstoneEventからTNTを起爆しないようにするのは不可能（らしい）
TNTは起爆するとエンティティになる→レッドストーンの変更を検知できない→"爆発しないように"することもできない
しかし、起爆するとTNTには物理演算が動くそうで、物理演算が動いたとき発火するイベントが用意されている
このイベントをキャンセルすると起爆しなくなる（らしい）
但し、全ての物理演算に対してこのイベントが発火するためサーバーが重くなる可能性があるのですがどうしましょう

**Comment by Xeltica** [comment]
Paper APIのこれ使えるかもしれなき
https://papermc.io/javadocs/paper/1.17/com/destroystokyo/paper/event/block/TNTPrimeEvent.html

PrimeReason.REDSTONE っていう都合の良いヤツがある
