### ISSUE TITLE
Maven→Gradle

### ISSUE THREAD

**Issue by Xeltica** [XelticaMC/X-Core#82]
開発者がGradleに慣れていることと、Kotlin移行のついでに移行したい

- Gradleで自動的にpomからbuild.gradleに移行する
- pom.xmlを削除

CircleCIの自動デプロイが動かなくなるけど、別issueで修正作業をします

**Comment by kumitatepazuru** [comment]
nukkitのMavenリポジトリが502なので復活次第PRするつもりですが明日になる可能性が高そうです
